chore:actions updated

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -106,13 +106,13 @@ jobs:
     needs: build-and-push-ecr-image
     runs-on: self-hosted
     steps:
-      - name: Clean up disk space
-        run: |
-          docker system prune -af --volumes
-          docker image prune -af
-          sudo rm -rf /var/lib/docker || true
-          sudo rm -rf /tmp/*
-          sudo apt-get clean
+      # - name: Clean up disk space
+      #   run: |
+      #     docker system prune -af --volumes
+      #     docker image prune -af
+      #     sudo rm -rf /var/lib/docker || true
+      #     sudo rm -rf /tmp/*
+      #     sudo apt-get clean
 
       - name: Checkout
         uses: actions/checkout@v3
@@ -133,13 +133,13 @@ jobs:
       - name: Pull latest Docker image
         run: |
           # Remove old images before pulling new one
-          docker image prune -af
+          # docker image prune -af
           docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest
 
-      - name: Stop and remove existing container
-        run: |
-          docker stop $(docker ps -q --filter ancestor=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}) || true
-          docker rm $(docker ps -aq --filter ancestor=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}) || true
+      # - name: Stop and remove existing container
+      #   run: |
+      #     docker stop $(docker ps -q --filter ancestor=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}) || true
+      #     docker rm $(docker ps -aq --filter ancestor=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}) || true
 
       - name: Run Docker Image to Serve Users
         run: |
